name: Download File

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at 00:00 UTC

jobs:
  download_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download file
      run: |
        curl -L "https://raw.githubusercontent.com/Maasea/sgmodule/master/YoutubeAds.sgmodule" -o "Module/SurgeMd/YoutubeAds.sgmodule"

    - name: Commit and push if it changed
      run: |
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Updated YoutubeAds.sgmodule"
        git push